- name: set fact
  set_fact:
    __path: ""

- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- name: setup elastic
  include_tasks: setup_elastic.yaml
  when: inventory_hostname in groups["work_master"]
