- name: set fact
  set_fact:
    __path: ""
    __kafka: "{{ log.kafka.bootstrap_servers }}"

- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- block:
  - name: set kafka fact
    set_fact:
      __kafka: ["{{ service.kafka.name }}.{{ service.namespace}}:9092"]
  - name: include kafka role
    include_role:
      name: kafka
  when: log.kafka.enabled

- name: setup elastic
  include_tasks: setup_elastic.yaml
