apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter

  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: exporter
        image: harbor.test.com/prometheus/blackbox-exporter:master
        ports:
        - containerPort: 9115
          protocol: TCP 
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitor
spec:
  selector:
    app: blackbox-exporter
  type: ClusterIP
  ports:
  - name: http
    port: 9115
    targetPort: 9115
