apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitor
  namespace: monitor
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:

      - path: /(prometheus(/.*)?$)
        backend:
          serviceName: prometheus-server
          servicePort: 80

      - path: /(alertmanager(/.*)?$)
        backend:
          serviceName: prometheus-alertmanager
          servicePort: 80

      - path: /(grafana(/.*)?$)
        backend:
          serviceName: grafana
          servicePort: 80

  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: k8s-ingress
