- name: install redis
  kubernetes.core.helm:
    chart_ref: "{{ __path }}{{ service.redis.chart.path }}"
    chart_repo_url: "{{ chart.repo['bitnami'] }}"
    chart_version: "{{ service.redis.chart.version }}"
    release_name: "{{ service.redis.name }}"
    release_namespace: "{{ service.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      image:
        registry: "{{ service.repository.strip('/') }}"
      password: "{{ service.redis.password }}"
