- name: check keepalived
  shell: docker ps -f name=keepalived | grep keepalived
  register: keepalived_installed
  ignore_errors: True

- block:
  - name: create dir
    file:
      name: /etc/keepalived
      state: directory

  - name: copy check.sh
    copy:
      src: check.sh
      dest: /etc/keepalived/
      mode: 755
  
  - name: config keepalived
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
  
  - name: start keepalived
    shell: "docker run --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW --net=host --name keepalived -d -v /etc/keepalived/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf -v /etc/keepalived:/etc/keepalived --restart always {{ keepalived.image }}"
  when: keepalived_installed.rc != 0
