apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: elastic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:

      - path: /(kibana(/.*)?$)
        backend:
          serviceName: kibana-kibana
          servicePort: 5601

  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: k8s-ingress
