apiVersion: extensions/v1beta1	
kind: Ingress	
metadata:	
  annotations:	
    cert-manager.io/cluster-issuer: {{ .Values.url.clusterissuer }}
    kubernetes.io/ingress.classb: nginx	
    nginx.ingress.kubernetes.io/rewrite-target: /$1	
#    nginx.ingress.kubernetes.io/ssl-redirect: 'false'	
  name: "{{ .Values.url.system }}-grafana"
  namespace: monitor
spec:	
  rules:	
    - host: aiops.staging.nari	
      http:	
        paths:	
          - backend:	
              serviceName: grafanatest	
              servicePort: 3000	
            path: /(grafana/.*)	
  tls:	
    - hosts:	
        - {{ .Values.url.host }}
      secretName: "{{ .Values.url.system }}-ingress"
