task_id: 8

ntp:
  server:
  - ntp.ntsc.ac.cn
  - ntp1.aliyun.com
  - 210.72.145.44

timezone: Asia/Shanghai

dns:
- 114.114.114.114
- 8.8.8.8

hosts:
- ip: 127.0.0.1
  hostname:
  - localhost

#if registry is changed,you should pay attention to registry_prefix
registry: "10.10.10.250"
#when registry is empty, this should be empty too
#must end with / or be empty
registry_prefix: "{{ registry }}/library/"

docker:
  version: 20.10.5
  containerd:
    sandbox_image: "{{ registry_prefix }}k8s.gcr.io/pause:3.6"
  insecure-registries: ["{{ registry }}"]
  registry-mirrors: []
  http_proxy:
    enabled: True
    server: http://10.10.10.250:8123
    #must include service and pod network: 10.0.0.0/8
    no_proxy: ["{{ registry }}", "10.0.0.0/8", "quay.io", "docker.com", "docker.io", "localhost", "127.0.0.1", "aliyuncs.com", "myhuaweicloud.com"]

kubernetes:
  version: 1.22.10
  repository: "{{ registry_prefix }}k8s.gcr.io"
  apiserver:
    control_plane:
      ip: 10.172.1.10
      port: 16443
    network:
      service_subnet: 10.96.0.0/12
      pod_subnet: 10.244.0.0/16
    nodeport_range: 10000-65535

calico:
  repository: "{{ registry_prefix }}"
  encapsulation: IPIP
  nodeAddressAutodetectionV4:
    cidrs:
    - "10.172.1.0/24"

nginx:
  image: "{{ registry_prefix }}nginx:latest"
  health_check:
    port: 16442

keepalived:
  id: 120
  vip: "{{ kubernetes.apiserver.control_plane.ip }}"
  health_check:
    url: "http://127.0.0.1:{{ nginx.health_check.port }}/"
  image: "{{ registry_prefix }}osixia/keepalived:latest"


#nfs config
nfs:
  server: ""
  path: ""
  image: "{{ registry_prefix }}nfs-server-alpine:12"

chart:
  repo:
    prometheus-community: https://prometheus-community.github.io/helm-charts
    grafana: https://grafana.github.io/helm-charts
  #if the charts are local, set the absoulte path here(e.g. /home/lil/prometheus)
  #then chart url and chart version won't work
  #must end with /
  path: ""

monitor:
  namespace: monitor
  repository: "{{ registry_prefix }}"
  #use default sc when set null
  storage_class: null
  prometheus:
    name: prometheus
    chart:
      #the path is relative path
      path: "prometheus"
      version: "15.8.5"
    blackbox:
      name: "blackbox-exporter"
      chart:
        path: "prometheus-blackbox-exporter"
        version: "5.7.0"
    adapter:
      name: "prometheus-adapter"
      chart:
        path: "prometheus-adapter"
        version: "3.2.2"
    grafana:
      name: "grafana"
      chart:
        path: "grafana"
        version: "6.28.0"
      dashboards:
        default:
          node-exporter:
            gnetId: 8919
            revision: 24
            datasource: Prometheus
          blackbox-exporter:
            gnetId: 7587
            revision: 3
            datasource: Prometheus


#basic service
metrics_server:
  repository: "{{ registry_prefix }}k8s.gcr.io/metrics-server/metrics-server"

nginx_ingress:
  controller:
    repository: "{{ registry_prefix }}quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
  defaultBackend:
    repository: "{{ registry_prefix }}k8s.gcr.io/defaultbackend-amd64"

cert_manager:
  cainjector:
    repository: "{{ registry_prefix }}quay.io/jetstack/cert-manager-cainjector"
  controller:
    repository: "{{ registry_prefix }}quay.io/jetstack/cert-manager-controller"
  webhook:
    repository: "{{ registry_prefix }}quay.io/jetstack/cert-manager-webhook"

nfs_provisioner:
  repository: "{{ registry_prefix }}nfs-client-provisioner"


#create storageClass
storage_class:
  tidb:
    pd: tidb-pd
    tikv: tidb-tikv
  prometheus: nfs-client


tidb:
  operator:
    image: "{{ registry_prefix }}tidb-operator:v1.1.10"
    scheduler_repository: "{{ registry_prefix }}kube-scheduler"
  discovery:
    image: "{{ registry_prefix }}tidb-operator:v1.1.10"
  pd:
    image: "{{ registry_prefix }}pd:v4.0.10"
    storage_class: "{{ storage_class.tidb.pd }}"
  tikv:
    image: "{{ registry_prefix }}tikv:v4.0.10"
    storage_class: "{{ storage_class.tidb.tikv }}"
  tidb:
    image: "{{ registry_prefix }}tidb:v4.0.10"
  busybox:
    image: "{{ registry_prefix }}busybox:1.31.1"
  mysql_client:
    image: "{{ registry_prefix }}mysqlclient:v1.4.6"
  root_password: cangoal
  node_port: 14000

mysql:
  repository: "{{ registry_prefix }}mysql"
  root_password: cangoal
  node_port: 13306
  storage_class: nfs-client


kafka:
  repository: "{{ registry_prefix }}kafka"
  zookeeper:
    repository: "{{ registry_prefix }}zookeeper"
  replicas: 1
  ip: "{{ keepalived.vip }}"
  node_port: [19092]

redis:
  repository: "{{ registry_prefix }}redis"
  password: cangoal

prometheus:
  alertmanager:
    repository: "{{ registry_prefix }}alertmanager"
  configmapReload:
    repository: "{{ registry_prefix }}configmap-reload"
  nodeExporter:
    repository: "{{ registry_prefix }}node-exporter"
  pushgateway:
    repository: "{{ registry_prefix }}pushgateway"
  repository: "{{ registry_prefix }}prometheus"
  storage_class: "{{ storage_class.prometheus }}"

aiops:
  database: aiops_dev
