task_id: 8

ntp:
  server:
  - ntp.ntsc.ac.cn
  - ntp1.aliyun.com
  - 210.72.145.44

registry: 3.1.4.126

kubernetes:
  version: 1.23.1
  repository: "{{ registry }}/k8s.gcr.io"

calico:
  repository: "{{ registry }}"

keepalived:
  id: 120
  vip: 3.1.4.120
  image: "{{ registry }}/osixia/keepalived:latest"

docker:
  version: 20.10.5
  insecure-registries: ["{{ registry }}"]

#nfs config
nfs:
  server: ""
  path: ""
  image: "{{ registry }}/nfs-server-alpine:12"


#basic service
metrics_server:
  repository: "{{ registry }}/k8s.gcr.io/metrics-server/metrics-server"

nginx_ingress:
  controller:
    repository: "{{ registry }}/k8s.gcr.io/nginx-ingress-controller/controller"
  defaultBackend:
    repository: "{{ registry }}/k8s.gcr.io/defaultbackend-amd64"

cert_manager:
  cainjector:
    repository: "{{ registry }}/quay.io/jetstack/cert-manager-cainjector"
  controller:
    repository: "{{ registry }}/quay.io/jetstack/cert-manager-controller"
  webhook:
    repository: "{{ registry }}/quay.io/jetstack/cert-manager-webhook"

nfs_provisioner:
  repository: "{{ registry }}/nfs-client-provisioner"


#create storageClass
storage_class:
  tidb:
    pd: tidb-pd
    tikv: tidb-tikv
  prometheus: nfs-client


tidb:
  operator:
    image: "{{ registry }}/tidb-operator:v1.1.10"
    scheduler_repository: "{{ registry }}/kube-scheduler"
  discovery:
    image: "{{ registry }}/tidb-operator:v1.1.10"
  pd:
    image: "{{ registry }}/pd:v4.0.10"
    storage_class: "{{ storage_class.tidb.pd }}"
  tikv:
    image: "{{ registry }}/tikv:v4.0.10"
    storage_class: "{{ storage_class.tidb.tikv }}"
  tidb:
    image: "{{ registry }}/tidb:v4.0.10"
  busybox:
    image: "{{ registry }}/busybox:1.31.1"
  mysql_client:
    image: "{{ registry }}/mysqlclient:v1.4.6"
  root_password: cangoal
  node_port: 14000

mysql:
  repository: "{{ registry }}/mysql"
  root_password: cangoal
  node_port: 13306
  storage_class: nfs-client


kafka:
  repository: "{{ registry }}/kafka"
  zookeeper:
    repository: "{{ registry }}/zookeeper"
  replicas: 1
  ip: "{{ keepalived.vip }}"
  node_port: [19092]

redis:
  repository: "{{ registry }}/redis"
  password: cangoal

prometheus:
  alertmanager:
    repository: "{{ registry }}/alertmanager"
  configmapReload:
    repository: "{{ registry }}/configmap-reload"
  nodeExporter:
    repository: "{{ registry }}/node-exporter"
  pushgateway:
    repository: "{{ registry }}/pushgateway"
  repository: "{{ registry }}/prometheus"
  storage_class: "{{ storage_class.prometheus }}"

aiops:
  database: aiops_dev
