- hosts: localhost
  gather_facts: True
  tasks:
  - name: install kubeadm
    apt:
      name: "kubeadm={{ kubernetes.version }}-00"
      state: present
      update_cache: yes
  - name: get k8s images
    shell: "kubeadm config images list --kubernetes-version={{ kubernetes.version}} --image-repository={{ kubernetes.repository }}"
    register: result1

  - name: include vars
    include_vars:
      dir: ../roles/k8s/defaults
  - name: select calico version
    set_fact:
      result: "{% for c_v in calico_k8s %} {% for k_v in calico_k8s[c_v]['k8s'] %} {% if k_v in kubernetes.version %} {{ c_v }} {% endif %} {% endfor %}{% endfor %}"
  - name: select calico version
    set_fact:
      calico_version: "{{ result | trim }}"

  - name: include template certmanager
    include_tasks: ../roles/cert-manager/tasks/template.yaml

  - name: include template ingress nginx
    include_tasks: ../roles/ingress-nginx/tasks/template.yaml

  - name: include template prometheus
    include_tasks: ../roles/prometheus/tasks/template_prometheus.yaml

  - name: include template elastic
    include_tasks: ../roles/elastic/tasks/template_elastic.yaml

  - name: include template kafka
    include_tasks: ../roles/kafka/tasks/template_kafka.yaml

  - name: include template mysql
    include_tasks: ../roles/mysql/tasks/template_mysql.yaml

  - name: set images
    set_fact:
      my_dict:
        k8s: "{{ result1.stdout.split('\n') }}"
        others:
        - "{{ nginx.image }}"
        - "{{ keepalived.image }}"
        - "{{ docker.containerd.sandbox_image }}"
        calico: "{{ calico_k8s[calico_version]['images'] }}"
        certmanager: "{{ certmanager_images | unique }}"
        ingress_nginx: "{{ ingress_nginx_images | unique }}"
        prometheus: "{{ prometheus_images | unique }}"
        elastic: "{{ elastic_images | unique }}"
        kafka: "{{ kafka_images | unique }}"
        mysql: "{{ mysql_images | unique }}"

  - name: list_images
    debug:
      msg: "{{ my_dict }}"
