apiVersion: v1
kind: PersistentVolume
metadata:
  name: pd-node-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-pd
  local:
    path: /mnt/data/tidb/pd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv-node-4
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-tikv
  local:
    path: /mnt/data/tidb/tikv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pd-node-5
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-pd
  local:
    path: /mnt/data/tidb/pd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-5

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv-node-5
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-tikv
  local:
    path: /mnt/data/tidb/tikv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pd-node-6
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-pd
  local:
    path: /mnt/data/tidb/pd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-6

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv-node-6
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: tidb-tikv
  local:
    path: /mnt/data/tidb/tikv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-6
