- name: set fact
  set_fact:
    __path: ""
    __domain: "{{ ansible_host }}"

- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- name: set domain fact
  set_fact:
    __domain: "{{ log.kafka.domain }}"
  when: log.kafka.domain.strip() != ""

- name: setup kafka
  include_tasks: setup_kafka.yaml
