- name: install docker on debian
  include_tasks: debian.yaml
  when: ansible_distribution_file_variety == "Debian"

- name: install docker on redhat
  include_tasks: redhat.yaml
  when: ansible_distribution_file_variety == "RedHat"

- name: create docker dir
  file:
    path: /etc/docker
    state: directory

- name: config docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: start docker
  service:
    name: docker
    state: started

- name: reload docker
  service:
    name: docker
    state: reloaded
    enabled: True
