apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanatest
  labels:
    name: grafanatest
  namespace: monitor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafanatest
  name: grafanatest
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: grafanatest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafanatest
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
          # - name: GF_SECURITY_ADMIN_USER
          # valueFrom:
          #  secretKeyRef:
          #    key: user
          #    name: grafana-credentials
          # - name: GF_SECURITY_ADMIN_PASSWORD
          #valueFrom:
          #  secretKeyRef:
          #    key: password
          #    name: grafana-credentials
        image: docker.repo.local:5000/grafana:7.0.6
        imagePullPolicy: IfNotPresent
        name: grafanatest
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafanatest
