apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-node-10
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: prometheus-storage
  local:
    path: /mnt/data/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-10

