- block:
  - name: check data directory
    stat:
      path: /mnt/prometheus
    register: data_dir_info
  
  - block:
    - name: create vg
      shell: "vgcreate prometheus /dev/{{ block_device }}"
    - name: create lv
      shell: "lvcreate -l 100%VG prometheus -n data"
    - name: format lvs
      shell: mkfs.xfs /dev/prometheus/data
    - name: create prometheus dir
      file:
        path: /mnt/prometheus
        state: directory
    - name: mount prometheus
      mount:
        src: /dev/mapper/prometheus-data
        path: /mnt/prometheus
        state: mounted
        fstype: xfs
        boot: True
    when: data_dir_info.stat.exists == False or (data_dir_info.stat.exists == True and data_dir_info.stat.isdir == False)
  when: inventory_hostname in groups["prometheus"]

- block:
  - name: create pvs dir
    file:
      path: "{{ workdir }}/pvc"
      state: directory
  
  - name: copy local pv template
    template:
      src: prometheus_local_pv.yaml.j2
      dest: "{{ workdir }}/pvs/prometheus_local_pv.yaml"
  
  - name: install local pv
    shell: kubectl apply -f prometheus_local_pv.yaml
    args:
      chdir: "{{ workdir }}/pvs"
  when: inventory_hostname in groups["work_master"]
